default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Password123#@!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: salon_booking_development

test:
  <<: *default
  database: salon_booking_test

production:
  <<: *default
  database: salon_booking_production
  